on:
  schedule:
    - cron: "*/5 * * * *"
name: Stale Bot workflow
jobs:
  build:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: stale
        id: stale
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 20
          days-before-close: 10
          operations-per-run: 5000
          stale-issue-message: |
            Hey there!
            This issue has 
            Hiya!
            This issue has gone quiet. Spooky quiet. ðŸ‘»
            We get a lot of issues, so we currently close issues after 30 days of inactivity. Itâ€™s been at least 20 days since the last update here.
            If we missed this issue or if you want to keep it open, please reply here. You can also add the label "not stale" to keep this issue open!
            As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!
            Thanks for being a part of the Gatsby community! ðŸ’ªðŸ’œ
          close-message: |
            Hey again!
            Itâ€™s been 30 days since anything happened on this issue, so our friendly neighborhood robot (thatâ€™s me!) is going to close it.
            Please keep in mind that Iâ€™m only a robot, so if Iâ€™ve closed this issue in error, Iâ€™m `HUMAN_EMOTION_SORRY`. Please feel free to reopen this issue or create a new one if you need anything else.
            As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request. Check out [gatsby.dev/contribute](https://www.gatsbyjs.org/contributing/how-to-contribute/) for more information about opening PRs, triaging issues, and contributing!
            Thanks again for being part of the Gatsby community! ðŸ’ªðŸ’œ
          exempt-issue-labels: |
            not stale
